[2020-12-01 11:38:49 +0530] [11326] [INFO] Starting gunicorn 20.0.4
[2020-12-01 11:38:49 +0530] [11326] [INFO] Listening at: http://0.0.0.0:5000 (11326)
[2020-12-01 11:38:49 +0530] [11326] [INFO] Using worker: sync
[2020-12-01 11:38:49 +0530] [11329] [INFO] Booting worker with pid: 11329
[2020-12-01 11:38:49 +0530] [11330] [INFO] Booting worker with pid: 11330
[2020-12-01 11:38:49 +0530] [11331] [INFO] Booting worker with pid: 11331
[2020-12-01 11:42:08 +0530] [11326] [INFO] Handling signal: int
[2020-12-01 11:42:08 +0530] [11330] [INFO] Worker exiting (pid: 11330)
[2020-12-01 11:42:08 +0530] [11329] [INFO] Worker exiting (pid: 11329)
[2020-12-01 11:42:08 +0530] [11331] [INFO] Worker exiting (pid: 11331)
[2020-12-01 11:42:08 +0530] [11326] [INFO] Shutting down: Master
[2020-12-01 11:42:43 +0530] [11410] [INFO] Starting gunicorn 20.0.4
[2020-12-01 11:42:43 +0530] [11410] [INFO] Listening at: http://0.0.0.0:5000 (11410)
[2020-12-01 11:42:43 +0530] [11410] [INFO] Using worker: sync
[2020-12-01 11:42:43 +0530] [11413] [INFO] Booting worker with pid: 11413
[2020-12-01 11:42:43 +0530] [11414] [INFO] Booting worker with pid: 11414
[2020-12-01 11:42:43 +0530] [11415] [INFO] Booting worker with pid: 11415
[2020-12-01 11:43:12 +0530] [11410] [INFO] Handling signal: int
[2020-12-01 11:43:12 +0530] [11415] [INFO] Worker exiting (pid: 11415)
[2020-12-01 11:43:12 +0530] [11414] [INFO] Worker exiting (pid: 11414)
[2020-12-01 11:43:12 +0530] [11413] [INFO] Worker exiting (pid: 11413)
[2020-12-01 11:43:13 +0530] [11410] [INFO] Shutting down: Master
[2020-12-01 11:57:15 +0530] [11644] [INFO] Starting gunicorn 20.0.4
[2020-12-01 11:57:15 +0530] [11644] [INFO] Listening at: http://0.0.0.0:5000 (11644)
[2020-12-01 11:57:15 +0530] [11644] [INFO] Using worker: sync
[2020-12-01 11:57:15 +0530] [11647] [INFO] Booting worker with pid: 11647
[2020-12-01 11:57:15 +0530] [11648] [INFO] Booting worker with pid: 11648
[2020-12-01 11:57:15 +0530] [11650] [INFO] Booting worker with pid: 11650
[2020-12-01 11:57:26 +0530] [11644] [INFO] Handling signal: int
[2020-12-01 11:57:26 +0530] [11650] [INFO] Worker exiting (pid: 11650)
[2020-12-01 11:57:26 +0530] [11648] [INFO] Worker exiting (pid: 11648)
[2020-12-01 11:57:26 +0530] [11647] [INFO] Worker exiting (pid: 11647)
[2020-12-01 11:57:26 +0530] [11644] [INFO] Shutting down: Master
[2020-12-04 13:59:39 +0530] [15432] [INFO] Starting gunicorn 20.0.4
[2020-12-04 13:59:39 +0530] [15432] [INFO] Listening at: http://0.0.0.0:5000 (15432)
[2020-12-04 13:59:39 +0530] [15432] [INFO] Using worker: sync
[2020-12-04 13:59:39 +0530] [15435] [INFO] Booting worker with pid: 15435
[2020-12-04 13:59:39 +0530] [15437] [INFO] Booting worker with pid: 15437
[2020-12-04 13:59:39 +0530] [15439] [INFO] Booting worker with pid: 15439
[2020-12-04 13:59:53 +0530] [15432] [INFO] Handling signal: int
[2020-12-04 13:59:53 +0530] [15435] [INFO] Worker exiting (pid: 15435)
[2020-12-04 13:59:53 +0530] [15439] [INFO] Worker exiting (pid: 15439)
[2020-12-04 13:59:53 +0530] [15437] [INFO] Worker exiting (pid: 15437)
[2020-12-04 13:59:54 +0530] [15432] [INFO] Shutting down: Master
[2020-12-04 14:11:20 +0530] [15658] [INFO] Starting gunicorn 20.0.4
[2020-12-04 14:11:20 +0530] [15658] [INFO] Listening at: http://0.0.0.0:5000 (15658)
[2020-12-04 14:11:20 +0530] [15658] [INFO] Using worker: sync
[2020-12-04 14:11:20 +0530] [15661] [INFO] Booting worker with pid: 15661
[2020-12-04 14:11:20 +0530] [15662] [INFO] Booting worker with pid: 15662
[2020-12-04 14:11:20 +0530] [15664] [INFO] Booting worker with pid: 15664
[2020-12-04 14:11:20 +0530] [15661] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/cQube/development/python/server.py", line 1, in <module>
    from views import *
  File "/home/ubuntu/cQube/development/python/views.py", line 343, in <module>
    @app.route('/infra_score', methods=['GET'])
  File "/home/ubuntu/new/lib/python3.6/site-packages/flask/app.py", line 1315, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/home/ubuntu/new/lib/python3.6/site-packages/flask/app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/ubuntu/new/lib/python3.6/site-packages/flask/app.py", line 1284, in add_url_rule
    "existing endpoint function: %s" % endpoint
AssertionError: View function mapping is overwriting an existing endpoint function: get_infra_score
[2020-12-04 14:11:20 +0530] [15661] [INFO] Worker exiting (pid: 15661)
[2020-12-04 14:11:20 +0530] [15662] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/cQube/development/python/server.py", line 1, in <module>
    from views import *
  File "/home/ubuntu/cQube/development/python/views.py", line 343, in <module>
    @app.route('/infra_score', methods=['GET'])
  File "/home/ubuntu/new/lib/python3.6/site-packages/flask/app.py", line 1315, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/home/ubuntu/new/lib/python3.6/site-packages/flask/app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/ubuntu/new/lib/python3.6/site-packages/flask/app.py", line 1284, in add_url_rule
    "existing endpoint function: %s" % endpoint
AssertionError: View function mapping is overwriting an existing endpoint function: get_infra_score
[2020-12-04 14:11:20 +0530] [15662] [INFO] Worker exiting (pid: 15662)
[2020-12-04 14:11:20 +0530] [15664] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/cQube/development/python/server.py", line 1, in <module>
    from views import *
  File "/home/ubuntu/cQube/development/python/views.py", line 343, in <module>
    @app.route('/infra_score', methods=['GET'])
  File "/home/ubuntu/new/lib/python3.6/site-packages/flask/app.py", line 1315, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/home/ubuntu/new/lib/python3.6/site-packages/flask/app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/ubuntu/new/lib/python3.6/site-packages/flask/app.py", line 1284, in add_url_rule
    "existing endpoint function: %s" % endpoint
AssertionError: View function mapping is overwriting an existing endpoint function: get_infra_score
[2020-12-04 14:11:20 +0530] [15664] [INFO] Worker exiting (pid: 15664)
[2020-12-04 14:11:21 +0530] [15658] [INFO] Shutting down: Master
[2020-12-04 14:11:21 +0530] [15658] [INFO] Reason: Worker failed to boot.
[2020-12-04 14:12:00 +0530] [15716] [INFO] Starting gunicorn 20.0.4
[2020-12-04 14:12:00 +0530] [15716] [INFO] Listening at: http://0.0.0.0:5000 (15716)
[2020-12-04 14:12:00 +0530] [15716] [INFO] Using worker: sync
[2020-12-04 14:12:00 +0530] [15719] [INFO] Booting worker with pid: 15719
[2020-12-04 14:12:00 +0530] [15720] [INFO] Booting worker with pid: 15720
[2020-12-04 14:12:00 +0530] [15722] [INFO] Booting worker with pid: 15722
[2020-12-04 14:33:24 +0530] [15716] [INFO] Handling signal: hup
[2020-12-04 14:33:24 +0530] [15716] [INFO] Hang up: Master
[2020-12-04 14:33:24 +0530] [16003] [INFO] Booting worker with pid: 16003
[2020-12-04 14:33:24 +0530] [16004] [INFO] Booting worker with pid: 16004
[2020-12-04 14:33:24 +0530] [15719] [INFO] Worker exiting (pid: 15719)
[2020-12-04 14:33:24 +0530] [15720] [INFO] Worker exiting (pid: 15720)
[2020-12-04 14:33:24 +0530] [15722] [INFO] Worker exiting (pid: 15722)
[2020-12-04 14:33:24 +0530] [16005] [INFO] Booting worker with pid: 16005
[2020-12-04 14:33:25 +0530] [16003] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/cQube/development/python/server.py", line 1, in <module>
    from views import *
  File "/home/ubuntu/cQube/development/python/views.py", line 347, in <module>
    @app.route('/', methods=['GET'])
  File "/home/ubuntu/new/lib/python3.6/site-packages/flask/app.py", line 1315, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/home/ubuntu/new/lib/python3.6/site-packages/flask/app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/ubuntu/new/lib/python3.6/site-packages/flask/app.py", line 1284, in add_url_rule
    "existing endpoint function: %s" % endpoint
AssertionError: View function mapping is overwriting an existing endpoint function: get_test
[2020-12-04 14:33:25 +0530] [16003] [INFO] Worker exiting (pid: 16003)
[2020-12-04 14:33:25 +0530] [16004] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/cQube/development/python/server.py", line 1, in <module>
    from views import *
  File "/home/ubuntu/cQube/development/python/views.py", line 347, in <module>
    @app.route('/', methods=['GET'])
  File "/home/ubuntu/new/lib/python3.6/site-packages/flask/app.py", line 1315, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/home/ubuntu/new/lib/python3.6/site-packages/flask/app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/ubuntu/new/lib/python3.6/site-packages/flask/app.py", line 1284, in add_url_rule
    "existing endpoint function: %s" % endpoint
AssertionError: View function mapping is overwriting an existing endpoint function: get_test
[2020-12-04 14:33:25 +0530] [16004] [INFO] Worker exiting (pid: 16004)
[2020-12-04 14:33:25 +0530] [16005] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/new/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/cQube/development/python/server.py", line 1, in <module>
    from views import *
  File "/home/ubuntu/cQube/development/python/views.py", line 347, in <module>
    @app.route('/', methods=['GET'])
  File "/home/ubuntu/new/lib/python3.6/site-packages/flask/app.py", line 1315, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/home/ubuntu/new/lib/python3.6/site-packages/flask/app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/ubuntu/new/lib/python3.6/site-packages/flask/app.py", line 1284, in add_url_rule
    "existing endpoint function: %s" % endpoint
AssertionError: View function mapping is overwriting an existing endpoint function: get_test
[2020-12-04 14:33:25 +0530] [16005] [INFO] Worker exiting (pid: 16005)
[2020-12-04 14:33:25 +0530] [15716] [INFO] Shutting down: Master
[2020-12-04 14:33:25 +0530] [15716] [INFO] Reason: Worker failed to boot.
[2020-12-04 14:34:08 +0530] [16049] [INFO] Starting gunicorn 20.0.4
[2020-12-04 14:34:08 +0530] [16049] [INFO] Listening at: http://0.0.0.0:5000 (16049)
[2020-12-04 14:34:08 +0530] [16049] [INFO] Using worker: sync
[2020-12-04 14:34:08 +0530] [16052] [INFO] Booting worker with pid: 16052
[2020-12-04 14:34:08 +0530] [16053] [INFO] Booting worker with pid: 16053
[2020-12-04 14:34:09 +0530] [16054] [INFO] Booting worker with pid: 16054
[2020-12-04 23:00:03 +0530] [16049] [INFO] Handling signal: term
[2020-12-04 23:00:03 +0530] [16052] [INFO] Worker exiting (pid: 16052)
[2020-12-04 23:00:03 +0530] [16054] [INFO] Worker exiting (pid: 16054)
[2020-12-04 23:00:03 +0530] [16053] [INFO] Worker exiting (pid: 16053)
[2020-12-04 23:00:03 +0530] [16049] [INFO] Shutting down: Master
[2020-12-07 08:22:59 +0530] [6364] [INFO] Starting gunicorn 20.0.4
[2020-12-07 08:22:59 +0530] [6364] [INFO] Listening at: http://0.0.0.0:5000 (6364)
[2020-12-07 08:22:59 +0530] [6364] [INFO] Using worker: sync
[2020-12-07 08:22:59 +0530] [6367] [INFO] Booting worker with pid: 6367
[2020-12-07 08:22:59 +0530] [6368] [INFO] Booting worker with pid: 6368
[2020-12-07 08:22:59 +0530] [6371] [INFO] Booting worker with pid: 6371
[2020-12-07 23:00:02 +0530] [6364] [INFO] Handling signal: hup
[2020-12-07 23:00:02 +0530] [6364] [INFO] Hang up: Master
[2020-12-07 23:00:02 +0530] [663] [INFO] Booting worker with pid: 663
[2020-12-07 23:00:02 +0530] [6364] [INFO] Handling signal: term
[2020-12-07 23:00:02 +0530] [673] [INFO] Booting worker with pid: 673
[2020-12-07 23:00:02 +0530] [667] [INFO] Booting worker with pid: 667
[2020-12-07 23:00:04 +0530] [663] [INFO] Worker exiting (pid: 663)
[2020-12-07 23:00:32 +0530] [6364] [INFO] Shutting down: Master
